---

name: Integration Tests

on:
  push:

jobs:

  tls_build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel: 5
        go-version: [1.16.x, 1.17.x, 1.18.x]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: redis/redis
          path: redis
      - name: generate ssl certificates
        run: |
          cd redis
          ./utils/gen-test-certs.sh
          chmod a+r tests/tls/*
      - name: copy redisearch binary
        run: |
          docker run --rm --entrypoint cat redislabs/redisearch:edge /usr/lib/redis/modules/redisearch.so > redisearch.so
          docker run --rm --entrypoint cat redislabs/redisearch:edge /usr/lib/redis/modules/rejson.so > rejson.so
          chmod 755 *.so
      - name: Start redisearch docekr with tls
        run: |
          docker run -d -v $(pwd)/redisearch.so:/data/redisearch.so \
            -v $(pwd)/rejson.so:/data/rejson.so \
            -v $(pwd)/redis/tests/tls/:/data \
            -p 6379:6379 redisfab/redis:6.2-latest-x64-bullseye redis-server \
            --tls-port 6379 --port 0  \
            --tls-cert-file /data/redis.crt  \
            --tls-key-file /data/redis.key  \
            --tls-ca-cert-file /data/ca.crt \
            --tls-auth-clients no --loadmodule /data/redisearch.so --loadmodule /data/rejson.so

      - name : Run Examples
        run: |
          make examples TLS_CERT=redis/tests/tls/redis.crt TLS_KEY=redis/tests/tls/redis.key TLS_CACERT=redis/tests/tls/ca.crt

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel: 5
        go-version: [1.16.x, 1.17.x, 1.18.x]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - uses: actions/checkout@v3
      - name: Start redisearch docker
        run: |
          docker run -d -p 6379:6379 redislabs/redisearch:edge
      - run: make get
      - run: make checkfmt
      - run: make test
      - run: make godoc_examples
      - run: make coverage
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov)
