---
name: Integration Tests

on:
  push:

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}
      - uses: actions/checkout@v3
      - name: Start redisearch docker
        run: |
          docker run -d -p 6379:6379 redislabs/redisearch:edge
      - run: make get
      - run: make checkfmt
      - run: make test
      - run: make godoc_examples
      - run: make coverage
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov)
